apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats-server.conf: |
    jetstream {
      store_dir: nats
    
      # 1GB
      max_memory_store: 1073741824
    
      # 10GB
      max_file_store: 10737418240
    }

