apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifier-frontend
  name: notifier-frontend-nodeport-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32000
  selector:
    app: notifier-frontend
  type: NodePort
