apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifier-backend
  name: notifier-backend-nodeport-svc
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32002
  selector:
    app: notifier-backend
  type: NodePort
